name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # Only runs if the force-ci label is on.
  should_fully_validate:
    runs-on: ubuntu-latest
    if: github.event.action == 'labeled' && github.event.label.name == 'force-ci'
    steps:
    - run: echo "PR is targeting main or has the force-ci label"

  validated:
    needs: [should_fully_validate]
    runs-on: ubuntu-latest
    steps:
    - run: |
      gh api \
        --method PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/z2oh/gha-playground/check-runs/${{ github.run_id }} \
       -f "name=validated" -f "status=completed" -f "conclusion=success"